#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0xDBD2CE893E2D1C87 (cfeck@kde.org)
#
Name     : kde-dev-utils
Version  : 18.08.0
Release  : 1
URL      : https://download.kde.org/stable/applications/18.08.0/src/kde-dev-utils-18.08.0.tar.xz
Source0  : https://download.kde.org/stable/applications/18.08.0/src/kde-dev-utils-18.08.0.tar.xz
Source99 : https://download.kde.org/stable/applications/18.08.0/src/kde-dev-utils-18.08.0.tar.xz.sig
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-2.0 LGPL-2.0
Requires: kde-dev-utils-bin
Requires: kde-dev-utils-lib
Requires: kde-dev-utils-data
Requires: kde-dev-utils-license
Requires: kde-dev-utils-locales
BuildRequires : buildreq-cmake
BuildRequires : buildreq-kde

%description
No detailed description available

%package bin
Summary: bin components for the kde-dev-utils package.
Group: Binaries
Requires: kde-dev-utils-data
Requires: kde-dev-utils-license

%description bin
bin components for the kde-dev-utils package.


%package data
Summary: data components for the kde-dev-utils package.
Group: Data

%description data
data components for the kde-dev-utils package.


%package lib
Summary: lib components for the kde-dev-utils package.
Group: Libraries
Requires: kde-dev-utils-data
Requires: kde-dev-utils-license

%description lib
lib components for the kde-dev-utils package.


%package license
Summary: license components for the kde-dev-utils package.
Group: Default

%description license
license components for the kde-dev-utils package.


%package locales
Summary: locales components for the kde-dev-utils package.
Group: Default

%description locales
locales components for the kde-dev-utils package.


%prep
%setup -q -n kde-dev-utils-18.08.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1535195903
mkdir clr-build
pushd clr-build
%cmake ..
make  %{?_smp_mflags}
popd

%install
export SOURCE_DATE_EPOCH=1535195903
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/doc/kde-dev-utils
cp COPYING %{buildroot}/usr/share/doc/kde-dev-utils/COPYING
cp COPYING.LIB %{buildroot}/usr/share/doc/kde-dev-utils/COPYING.LIB
pushd clr-build
%make_install
popd
%find_lang kuiviewer
%find_lang kpartloader

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/kpartloader
/usr/bin/kuiviewer

%files data
%defattr(-,root,root,-)
/usr/share/applications/org.kde.kuiviewer.desktop
/usr/share/icons/hicolor/128x128/apps/kuiviewer.png
/usr/share/icons/hicolor/16x16/apps/kuiviewer.png
/usr/share/icons/hicolor/32x32/apps/kuiviewer.png
/usr/share/icons/hicolor/48x48/apps/kuiviewer.png
/usr/share/icons/hicolor/64x64/apps/kuiviewer.png
/usr/share/icons/hicolor/scalable/apps/kuiviewer.svg
/usr/share/kservices5/designerthumbnail.desktop
/usr/share/kservices5/kuiviewer_part.desktop
/usr/share/kxmlgui5/kpartloader/kpartloaderui.rc
/usr/share/kxmlgui5/kuiviewer/kuiviewerui.rc
/usr/share/kxmlgui5/kuiviewerpart/kuiviewer_part.rc

%files lib
%defattr(-,root,root,-)
/usr/lib64/qt5/plugins/kuiviewerpart.so
/usr/lib64/qt5/plugins/quithumbnail.so

%files license
%defattr(-,root,root,-)
/usr/share/doc/kde-dev-utils/COPYING
/usr/share/doc/kde-dev-utils/COPYING.LIB

%files locales -f kuiviewer.lang -f kpartloader.lang
%defattr(-,root,root,-)

